[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://ec2-16-176-22-21.ap-southeast-2.compute.amazonaws.com:3000/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
